stages:
  - publish

publish:
  stage: publish
  image: node:16
  tags:
    - dind
  before_script:
    - echo "//10.115.1.100:30873/:_authToken=${VERDACCIO_TOKEN}" > ~/.npmrc
  script:
    - npm install
    - npm run build
    - npm publish --registry http://10.115.1.100:30873/
